fix: fetch assembly versions from current sdk

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -19,17 +19,12 @@ defaults_test: &defaults_test
     test_type:
       type: enum
       enum: [ "unit", "smoke" ]
-    dotnet_version:
-      type: string
 
 matrix_unix_node_version: &matrix_unix_node_version
   node_version: [ "16.20", "18.16", "20.3" ]
 
 matrix_windows_node_version: &matrix_windows_node_version
   node_version: [ "16.20.0", "18.16.0", "20.3.1" ]
-
-matrix_dotnet_version: &matrix_dotnet_version
-  dotnet_version: [ "9.0", "8.0", "7.0", "6.0" ]
 
 filters_branches_only_main: &filters_branches_only_main
   filters:
@@ -71,13 +66,11 @@ commands:
       os:
         type: enum
         enum: [ "unix", "windows" ]
-      dotnet_version:
-        type: string
     steps:
       - restore_cache:
           name: Restore Dotnet executable
           keys:
-            - dotnet-cli-{{ arch }}-{{<< parameters.dotnet_version >>}}-v3
+            - dotnet-cli-{{ arch }}-v3
       - when:
           condition:
             equal: [ "unix", << parameters.os >> ]
@@ -85,15 +78,23 @@ commands:
             - run:
                 name: Download and install dotnet
                 command: |
-                  if ! command -v dotnet &> /dev/null
-                  then
-                    echo "dotnet could not be found, downloading and installing"
-                    curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel << parameters.dotnet_version >> --install-dir ~/.local/apps/dotnet
-                    ln -s ~/.local/apps/dotnet/dotnet ~/.local/bin/
-                    exit
-                  fi
+                      DOTNET_VERSIONS=("9.0" "8.0" "7.0" "6.0")
+
+                      if ! command -v dotnet &> /dev/null
+                      then
+                        echo "dotnet could not be found or was of wrong version, removing existing and downloading new"
+                        
+                        for version in "${DOTNET_VERSIONS[@]}"; do
+                          echo "Installing .NET $version..."
+                          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel "$version" --install-dir ~/.local/apps/dotnet
+                          ln -s ~/.local/apps/dotnet/dotnet ~/.local/bin/
+                        done
+
+                        ln -s "$DOTNET_INSTALL_DIR/dotnet" "$BIN_DIR/"
+                        exit
+                      fi
             - save_cache:
-                key: dotnet-cli-{{ arch }}-{{<< parameters.dotnet_version >>}}-v3
+                key: dotnet-cli-{{ arch }}-v3
                 paths:
                   - ~/.local/apps/dotnet
                   - ~/.local/bin/dotnet
@@ -105,16 +106,22 @@ commands:
                 name: Download and install dotnet
                 # dotnet is already installed on Windows, so we can't check by just running it. Need to validate the version it returns.
                 command: |
-                  if [[ ! $(dotnet --version 2>&1) =~ ^<< parameters.dotnet_version >> ]]
-                  then
-                    echo "dotnet could not be found or was of wrong version, removing existing and downloading new"
-                    rm -rf "C:\Program Files\dotnet"
-                    curl -sSL https://dot.net/v1/dotnet-install.ps1 > dotnet-install.ps1
-                    powershell -File dotnet-install.ps1 -Channel << parameters.dotnet_version >> -InstallDir "C:\Program Files\dotnet"
-                  fi
+                   DOTNET_VERSIONS=("9.0" "8.0" "7.0" "6.0")
+                      DOTNET_INSTALL_DIR="$HOME/.local/apps/dotnet"
+                      BIN_DIR="$HOME/.local/bin"
+
+                      if ! command -v dotnet &> /dev/null
+                      then
+                        echo "dotnet could not be found or was of wrong version, removing existing and downloading new"
+                        rm -rf "C:\Program Files\dotnet"
+                        for version in "${DOTNET_VERSIONS[@]}"; do
+                          curl -sSL https://dot.net/v1/dotnet-install.ps1 > dotnet-install.ps1
+                          powershell -File dotnet-install.ps1 -Channel "$version" -InstallDir "C:\Program Files\dotnet"
+                        done
+                      fi
                 shell: bash.exe
             - save_cache:
-                key: dotnet-cli-{{ arch }}-{{<< parameters.dotnet_version >>}}-v3
+                key: dotnet-cli-{{ arch }}-v3
                 paths:
                   - C:\Program Files\dotnet
 
@@ -168,7 +175,6 @@ jobs:
       - checkout
       - install_dotnet:
           os: "windows"
-          dotnet_version: << parameters.dotnet_version >>
       - show_dotnet_version
       - node/install
       - node_install_packages
@@ -188,7 +194,6 @@ jobs:
       - checkout
       - install_dotnet:
           os: "unix"
-          dotnet_version: << parameters.dotnet_version >>
       - show_dotnet_version
       - node_install_packages
       - show_node_version
@@ -239,7 +244,6 @@ workflows:
             parameters:
               <<: *matrix_unix_node_version
               test_type: [ "unit" ]
-              dotnet_version: [ "9.0" ]
           name: Unix Unit Tests for Node=<< matrix.node_version >>
           context: nodejs-install
           node_version: "<< matrix.node_version >>"
@@ -251,10 +255,9 @@ workflows:
           matrix:
             alias: test-unix-smoke
             parameters:
-              <<: *matrix_dotnet_version
               test_type: [ "smoke" ]
               node_version: [ "lts" ]
-          name: Unix Smoke Tests for Node=<< matrix.node_version >>-Dotnet=<< matrix.dotnet_version >>
+          name: Unix Smoke Tests for Node=<< matrix.node_version >>
           context: nodejs-install
           node_version: "<< matrix.node_version >>"
           requires:
@@ -267,7 +270,6 @@ workflows:
             parameters:
               <<: *matrix_windows_node_version
               test_type: [ "unit" ]
-              dotnet_version: [ "9.0" ]
           name: Windows Unit Tests for Node=<< matrix.node_version >>
           context: nodejs-install
           node_version: "<< matrix.node_version >>"
@@ -279,10 +281,9 @@ workflows:
           matrix:
             alias: test-windows-smoke
             parameters:
-              <<: *matrix_dotnet_version
               test_type: [ "smoke" ]
               node_version: [ "lts" ]
-          name: Windows Smoke Tests for Node=<< matrix.node_version >>-Dotnet=<< matrix.dotnet_version >>
+          name: Windows Smoke Tests for Node=<< matrix.node_version >>
           context: nodejs-install
           node_version: "<< matrix.node_version >>"
           requires:
