fix: added net8.0 test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,6 +1,7 @@
 version: 2.1
 
 orbs:
+  node: circleci/node@5.1.0
   win: circleci/windows@5.0.0
   prodsec: snyk/prodsec-orb@1.0
 
@@ -10,7 +11,6 @@ defaults: &defaults
       type: string
       default: ''
   working_directory: ~/snyk-nuget-plugin
-
 
 matrix_unix_node_version: &matrix_unix_node_version
   node_version: ["16.20", "18.16", "20.3"]
@@ -25,31 +25,29 @@ windows_defaults: &windows_defaults
     name: win/default
     shell: bash
 
-commands:
-  install_deps:
-    description: Install dependencies
-    steps:
-      - run:
-          name: Install dependencies
-          command: npm install
+filters_branches_only_main: &filters_branches_only_main
+  filters:
+    branches:
+      only:
+        - main
 
-  install_node_npm:
-    description: Install correct Node version
-    parameters:
-      node_version:
-        type: string
-        default: ''
+filters_branches_ignore_main: &filters_branches_ignore_main
+  filters:
+    branches:
+      ignore:
+        - main
+
+commands:
+  node_install_packages:
+    description: Install NPM packages
     steps:
       - run:
-          name: Install correct version of Node
-          command: |
-            nvm install << parameters.node_version >>
-      - run:
-          name: Use correct version of Node
-          command: |
-            set -e
-            nvm list
-            nvm use << parameters.node_version >>
+          # The Node orb handles all the boring work for us, but they do not understand repos with no package-lock.json
+          name: Create fake package-lock.json
+          command: touch package-lock.json
+      - node/install-packages:
+          cache-only-lockfile: false
+          override-ci-command: npm i
 
   show_node_version:
     description: Log Node and npm version
@@ -64,6 +62,9 @@ commands:
   install_dotnet:
     description: Install the dotnet CLI
     parameters:
+      os:
+        type: enum
+        enum: ['unix', 'windows']
       dotnet_version:
         type: string
         default: '8.0'
@@ -71,22 +72,46 @@ commands:
       - restore_cache:
           name: Restore Dotnet executable
           keys:
-            - dotnet-cli-{{ arch }}-{{ .Branch }}-{{<< parameters.dotnet_version >>}}
-      - run:
-          name: Download and install dotnet
-          command: |
-            if ! command -v dotnet &> /dev/null
-            then
-              echo "dotnet could not be found, downloading and installing"
-              curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel << parameters.dotnet_version >> --install-dir ~/.local/apps/dotnet
-              ln -s ~/.local/apps/dotnet/dotnet ~/.local/bin/
-              exit
-            fi
-      - save_cache:
-          key: dotnet-cli-{{ arch }}-{{ .Branch }}-{{<< parameters.dotnet_version >>}}
-          paths:
-            - ~/.local/apps/dotnet
-            - ~/.local/bin/dotnet
+            - dotnet-cli-{{ arch }}-{{<< parameters.dotnet_version >>}}-v3
+      - when:
+          condition:
+            equal: [ 'unix', << parameters.os >> ]
+          steps:
+          - run:
+              name: Download and install dotnet
+              command: |
+                if ! command -v dotnet &> /dev/null
+                then
+                  echo "dotnet could not be found, downloading and installing"
+                  curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel << parameters.dotnet_version >> --install-dir ~/.local/apps/dotnet
+                  ln -s ~/.local/apps/dotnet/dotnet ~/.local/bin/
+                  exit
+                fi
+          - save_cache:
+              key: dotnet-cli-{{ arch }}-{{<< parameters.dotnet_version >>}}-v3
+              paths:
+                - ~/.local/apps/dotnet
+                - ~/.local/bin/dotnet
+      - when:
+          condition:
+            equal: [ 'windows', << parameters.os >> ]
+          steps:
+            - run:
+                name: Download and install dotnet
+                # dotnet is already installed on Windows, so we can't check by just running it. Need to validate the version it returns.
+                command: |
+                  if [[ ! $(dotnet --version 2>&1) =~ ^<< parameters.dotnet_version >> ]]
+                  then
+                    echo "dotnet could not be found or was of wrong version, removing existing and downloading new"
+                    rm -rf "C:\Program Files\dotnet"
+                    curl -sSL https://dot.net/v1/dotnet-install.ps1 > dotnet-install.ps1
+                    powershell -File dotnet-install.ps1 -Channel << parameters.dotnet_version >> -InstallDir "C:\Program Files\dotnet"
+                  fi
+                shell: bash.exe
+            - save_cache:
+                key: dotnet-cli-{{ arch }}-{{<< parameters.dotnet_version >>}}-v3
+                paths:
+                  - C:\Program Files\dotnet
 
   show_dotnet_version:
     description: Log Dotnet version
@@ -102,7 +127,7 @@ jobs:
       - image: cimg/node:<< parameters.node_version >>
     steps:
       - checkout
-      - install_deps
+      - node_install_packages
       - show_node_version
       - run:
           name: Run lint
@@ -116,9 +141,11 @@ jobs:
     steps:
       - run: git config --global core.autocrlf false
       - checkout
-      - install_node_npm:
-          node_version: << parameters.node_version >>
-      - install_deps
+      - install_dotnet:
+          os: 'windows'
+      - show_dotnet_version
+      - node/install
+      - node_install_packages
       - show_node_version
       - run:
           name: Run tests
@@ -133,10 +160,11 @@ jobs:
       - image: cimg/node:<< parameters.node_version >>
     steps:
       - checkout
-      - install_deps
-      - show_node_version
-      - install_dotnet
+      - install_dotnet:
+          os: 'unix'
       - show_dotnet_version
+      - node_install_packages
+      - show_node_version
       - run:
           name: Run tests
           command: npm test
@@ -148,7 +176,7 @@ jobs:
     resource_class: small
     steps:
       - checkout
-      - install_deps
+      - node_install_packages
       - run:
           name: Publish to GitHub
           command: npx semantic-release
@@ -162,11 +190,13 @@ workflows:
           context:
             - snyk-bot-slack
           channel: os-team-managed-alerts
+          <<: *filters_branches_ignore_main
 
       - lint:
           name: Lint
           context: nodejs-install
           node_version: '16.20'
+          <<: *filters_branches_ignore_main
 
       # UNIX tests
       - test-unix:
@@ -179,6 +209,7 @@ workflows:
           node_version: "<< matrix.node_version >>"
           requires:
             - Lint
+          <<: *filters_branches_ignore_main
 
       # Windows tests
       - test-windows:
@@ -191,6 +222,8 @@ workflows:
           node_version: "<< matrix.node_version >>"
           requires:
             - Lint
+          <<: *filters_branches_ignore_main
+
 
       # Release
       - release:
@@ -201,7 +234,5 @@ workflows:
             - scan-repo
             - test-unix
             - test-windows
-          filters:
-            branches:
-              only:
-                - main
+          <<: *filters_branches_only_main
+
